"use client";

import { useEffect, useRef } from "react";

const THRESHOLD = 5;
const FRICTION = 0.95; // per 16ms frame — close to iOS's "normal" deceleration

/**
 * Lets mouse users pan an overflowing container by click-dragging, the way
 * touch users swipe, including an inertial glide after release. Touch/pen keep
 * native scrolling. A drag that moves more than a few px swallows the
 * following click so rows don't open by accident.
 */
export function useDragScroll<T extends HTMLElement>() {
  const ref = useRef<T>(null);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;

    let startX = 0;
    let startY = 0;
    let left = 0;
    let top = 0;
    let pointerId: number | null = null;
    let dragging = false;
    let samples: { t: number; x: number; y: number }[] = [];
    let raf = 0;

    const stopGlide = () => cancelAnimationFrame(raf);

    const glide = (vx: number, vy: number) => {
      let prev = performance.now();
      const step = (now: number) => {
        const frames = (now - prev) / 16;
        prev = now;
        el.scrollLeft -= vx * 16 * frames;
        el.scrollTop -= vy * 16 * frames;
        const decay = Math.pow(FRICTION, frames);
        vx *= decay;
        vy *= decay;
        if (Math.abs(vx) > 0.02 || Math.abs(vy) > 0.02) raf = requestAnimationFrame(step);
      };
      raf = requestAnimationFrame(step);
    };

    const onDown = (e: PointerEvent) => {
      stopGlide();
      if (e.pointerType !== "mouse" || e.button !== 0) return;
      if (el.scrollWidth <= el.clientWidth) return;
      // Leave interactive controls (checkboxes, menus) alone.
      if ((e.target as HTMLElement).closest("button, a, input, [role=checkbox]")) return;
      pointerId = e.pointerId;
      startX = e.clientX;
      startY = e.clientY;
      left = el.scrollLeft;
      top = el.scrollTop;
      dragging = false;
      samples = [{ t: e.timeStamp, x: e.clientX, y: e.clientY }];
    };

    const onMove = (e: PointerEvent) => {
      if (e.pointerId !== pointerId) return;
      const dx = e.clientX - startX;
      const dy = e.clientY - startY;
      if (!dragging && Math.hypot(dx, dy) < THRESHOLD) return;
      if (!dragging) {
        dragging = true;
        el.setPointerCapture(e.pointerId);
        el.style.cursor = "grabbing";
        el.style.userSelect = "none";
      }
      el.scrollLeft = left - dx;
      el.scrollTop = top - dy;
      samples.push({ t: e.timeStamp, x: e.clientX, y: e.clientY });
      if (samples.length > 5) samples.shift();
    };

    const onUp = (e: PointerEvent) => {
      if (e.pointerId !== pointerId) return;
      pointerId = null;
      el.style.cursor = "";
      el.style.userSelect = "";
      if (!dragging) return;
      dragging = false;
      if (el.hasPointerCapture(e.pointerId)) el.releasePointerCapture(e.pointerId);

      // Keep the flick's momentum (only if the pointer was still moving).
      const a = samples[0];
      const b = samples[samples.length - 1];
      const dt = b.t - a.t;
      if (dt > 0 && e.timeStamp - b.t < 60) glide((b.x - a.x) / dt, (b.y - a.y) / dt);

      // Swallow the click generated by this drag.
      const stop = (ev: MouseEvent) => {
        ev.stopPropagation();
        ev.preventDefault();
      };
      window.addEventListener("click", stop, { capture: true, once: true });
      setTimeout(() => window.removeEventListener("click", stop, { capture: true }), 0);
    };

    el.addEventListener("pointerdown", onDown);
    el.addEventListener("pointermove", onMove);
    el.addEventListener("pointerup", onUp);
    el.addEventListener("pointercancel", onUp);
    el.addEventListener("wheel", stopGlide, { passive: true });
    return () => {
      stopGlide();
      el.removeEventListener("pointerdown", onDown);
      el.removeEventListener("pointermove", onMove);
      el.removeEventListener("pointerup", onUp);
      el.removeEventListener("pointercancel", onUp);
      el.removeEventListener("wheel", stopGlide);
    };
  }, []);

  return ref;
}
